### ISSUE TITLE
Functions.cpp

### ISSUE THREAD

**Issue by Keheira** [Rockrat2008/cpp-project#1]
You program just skips over the rent function but other than that it works.

`

        #include "prog5.h"

        int enterHeroes(int currentHeroes, int &  maxHeroes, Heroes* &heroList)
        {
	int menuChoice = 0;

	if (currentHeroes == maxHeroes)
	{
		cout << "Sorry!  Your complex can only hold " << maxHeroes << " heroes.\nYou cannot add more.";
	}
	else
	{
		cout << "What do you want to do?\n";
		cout << "\t1.\tLoad the heroes from a file.\n";
		cout << "\t2.\tEnter a hero manually.\n";
		cout << "\tChooose 1 or 2.  ";
		cin >>  menuChoice;

		if(menuChoice < 1 || menuChoice > 2)  //  Loop to validate menu choice
		{
			cout << "\n \n That is not a valid option.  Please make a valid menu choice.  ";
			cin >> menuChoice;
		}

		switch(menuChoice)
		{
			case 1 :
			{
				string heroFile;
				
				cout << "\nWhat is the name of the file with your list of superheroes? (ex: filename.txt)\n";
				cout << "FILENAME:  ";
				cin >> heroFile;
				ifstream heroesFile;
				heroesFile.open(heroFile);
				
				if (!heroesFile)
				{
					cout << "There was an error with your heroes file.\n\n";
				}
				break;
			}	
			case 2 :
			{
				bool addMore = true, isDangerous;
				float rentAmt = 0, damageAmt = 0, nbrYears = 0;
				char addAnother;
				string name, description;
				do
				{
					cout << endl << endl << "SUPERHERO NAME:  ";
					cin.clear();
                                        cin.sync();
					cin>>name;
					//getline(std::cin, name);
					cout << endl << endl <<  "DESCRIPTION:  ";
					cin.clear();
					cin.sync();
					cin>>description;
					//getline(std::cin, description);
					cout << endl << endl << "IS IT A DANGEROUS HERO?  (y or n):  ";
					cin.clear();
					cin.sync();
					cin >> isDangerous;
					cout << endl << endl <<  "How much does pay for rent per month? \n RENT PRICE:  ";
					cin.clear();
					cin.sync();
					cin >> rentAmt;
					cout << endl << endl << "What is the typical damage has each month?";
					cout << endl << "DAMAGE COST:  ";
					cin.clear();
					cin.sync();
					cin >> damageAmt;
					cout << endl << endl <<  "How many years has lived in your condo?";
					cout << endl << "YEARS:  ";
					cin.clear();
					cin.sync();
					cin >> nbrYears;
					cout << "NAME:  " << name << endl;
					cout << "DESC:  " << description << endl;
					cout << "DANG:  " << isDangerous << endl;
					cout << "RENT:  " << rentAmt << endl;
					cout << "DAMG:  " << damageAmt << endl;
					cout << "YEAR:  " << nbrYears << endl;
					
					heroList[currentHeroes].name = name;
					heroList[currentHeroes].description = description;
					heroList[currentHeroes].dangerous = isDangerous;
					heroList[currentHeroes].rentInfo.rent = rentAmt;
					heroList[currentHeroes].rentInfo.damage = damageAmt;
					heroList[currentHeroes].rentInfo.years = nbrYears;
					
	 
					cout << endl << endl << "The " << name << " has been added.";
					currentHeroes++;
					cout << "Current heroes count " << currentHeroes;
					
					cout << endl << endl << "Want to add more heroes?  (y or n)  ";
					cin >> addAnother;
					
					if (addAnother == 'n' || addAnother == 'N')
					{
						addMore = false;
					}
					
				}while(addMore);
				
				return currentHeroes;
				
				break;
			}	
		}
	}}
`

**Comment by Rockrat2008** [comment]
Thanks for the help.
